### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by china-wyc** [Ragib-Amin-Nihal/C2A#1]
你好作者，为什么我用yolov10在训练结束后只有bent类别，其他的类别并没有训练到。查看train和test还有val的labels，是没有分明类别吗？

**Comment by Ragib-Amin-Nihal** [comment]
Sorry for the misunderstanding. The pose information can be found on the "All labels with Pose info" folder. The 6th value in every line represents the pose information.

**Comment by china-wyc** [comment]
作者你好，那train和test还有val文件夹中的labels标签是经过归一化的标签吗？

**Comment by Ragib-Amin-Nihal** [comment]
In the train, val and test folder, the annotation are given for "human". The bounding box are given in both coco and yolo format.

**Comment by china-wyc** [comment]
You may not understand what I mean, when I use the label in the 'train, test and val' folder, there is only the bent category after the training is completed, I checked the label folder in these three folders separately, and found that the first column of the txt file is all 0, and there are no categories 0, 1, 2, 3, 4, so the training only has 0 categories, and there are no other categories, I don't know if it's right to understand this way. Of course, the first folder has all the tags, and the sixth column has all the category information, should the last column be placed in the first column? Thank you to the author for taking the trouble to answer me, so this question has been bothering me.

**Comment by Ragib-Amin-Nihal** [comment]
I understand your confusion regarding the dataset structure and labeling. You're correct in your observation, and I can see why this is causing confusion. 
In this dataset:
1. "Human" is the main category (class 0) in the train, test, and val folders. This explains why all label files in these folders have 0 as the first value.
2. The pose values are sub-categories of the main "Human" class:( 0: Bent, 1: Kneeling, 2: Lying, 3: Sitting, 4: Upright)


Here's what you might want to do:

- If you want to train a model to detect different poses as separate classes, you should use the labels from the 'All labels with Pose info' folder, but modify them so that the pose category (currently in the sixth column) is moved to the first column.
- If you just want to detect people (without pose information), you can use the labels as they are in the 'train', 'test', and 'val' folders.

**Comment by china-wyc** [comment]
Thank you, I understand now!!!
&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月22日(星期天) 晚上8:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ragib-Amin-Nihal/C2A] labels (Issue #1)





 
I understand your confusion regarding the dataset structure and labeling. You're correct in your observation, and I can see why this is causing confusion.
 In this dataset:
  
"Human" is the main category (class 0) in the train, test, and val folders. This explains why all label files in these folders have 0 as the first value.
 
The pose values are indeed sub-categories of the main "Human" class:( 0: Bent, 1: Kneeling, 2: Lying, 3: Sitting, 4: Upright)
  
Here's what you might want to do:
  
If you want to train a model to detect different poses as separate classes, you should use the labels from the 'All labels with Pose info' folder, but modify them so that the pose category (currently in the sixth column) is moved to the first column.
 
If you just want to detect people (without pose information), you can use the labels as they are in the 'train', 'test', and 'val' folders.
  
&mdash;

**Comment by china-wyc** [comment]
谢谢，我知道了！！！
